=== saschanaz/garupa-events/schemas/data.schema.json
{
  "definitions": {
    "region": {
      "type": ["object", "null"],
      "title": "The Region Schema",
      "required": [
        "title",
        "start",
        "end"
      ],
      "properties": {
        "title": {
          "type": "string",
          "title": "The Title Schema",
          "examples": [
            "SAKURAï¼ŠBLOOMING PARTY!"
          ],
          "pattern": "^(.*)$"
        },
        "start": {
          "type": "string",
          "title": "The Start Schema",
          "examples": [
            "2017-03-24"
          ],
          "pattern": "^\\d{4}-\\d{2}-\\d{2}$"
        },
        "end": {
          "type": "string",
          "title": "The End Schema",
          "examples": [
            "2017-03-30"
          ],
          "pattern": "^\\d{4}-\\d{2}-\\d{2}$"
        }
      }
    },
    "meta": {
      "type": ["object", "null"],
      "title": "The Meta Schema",
      "properties": {
        "attribute": {
          "type": "string",
          "examples": [
            "pure"
          ],
          "enum": ["pure", "cool", "happy", "powerful"]
        },
        "dreamFestival": {
          "type": "object",
          "properties": {
            "linkId": {
              "type": "string"
            }
          }
        }
      }
    }
  },
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://example.com/root.json",
  "type": "array",
  "title": "The Root Schema",
  "items": {
    "$id": "#/items",
    "type": "object",
    "title": "The Items Schema",
    "required": [
      "linkId",
      "meta",
      "type",
      "region"
    ],
    "properties": {
      "linkId": {
        "$id": "#/items/properties/linkId",
        "type": ["string", "null"],
        "title": "The Linkid Schema",
        "examples": [
          "Sakura_Blooming_Party!"
        ]
      },
      "meta": {
        "$ref": "#/definitions/meta"
      },
      "type": {
        "type": "string",
        "title": "The Type Schema",
        "examples": [
          "normal"
        ],
        "enum": ["normal", "challenge", "versus", "try", "mission"]
      },
      "region": {
        "$id": "#/items/properties/region",
        "type": "object",
        "title": "The Region Schema",
        "required": [
          "japan",
          "taiwan",
          "korea",
          "global",
          "china"
        ],
        "properties": {
          "japan": {
            "$ref": "#/definitions/region"
          },
          "taiwan": {
            "$ref": "#/definitions/region"
          },
          "korea": {
            "$ref": "#/definitions/region"
          },
          "global": {
            "$ref": "#/definitions/region"
          },
          "china": {
            "$ref": "#/definitions/region"
          }
        }
      }
    }
  }
}

=== saschanaz/garupa-events/static/data.json
[
  {
    "linkId": "Sakura_Blooming_Party!",
    "meta": {
      "attribute": "pure"
    },
    "type": "normal",
    "region": {
      "japan": {
        "title": "SAKURA＊BLOOMING PARTY!",
        "start": "2017-03-24",
        "end": "2017-03-30"
      },
      "taiwan": {
        "title": "SAKURA＊BLOOMING PARTY",
        "start": "2017-10-12",
        "end": "2017-10-18"
      },
      "korea": {
        "title": "CHERRY☆BLOOMING PARTY!",
        "start": "2018-02-06",
        "end": "2018-02-12"
      },
      "global": {
        "title": "Sakura Blooming Party!",
        "start": "2018-04-05",
        "end": "2018-04-11"
      },
      "china": {
        "title": "SAKURA＊BLOOMING PARTY!",
        "start": "2019-06-11",
        "end": "2019-06-16"
      }
    }
  },
  {
    "linkId": "A_Song_Unfinished",
    "meta": {
      "attribute": "cool"
    },
    "type": "normal",
    "region": {
      "japan": {
        "title": "思い繋ぐ、未完成な歌",
        "start": "2017-04-05",
        "end": "2017-04-11"
      },
      "taiwan": {
        "title": "心意相繫，未完成的歌曲",
        "start": "2017-10-20",
        "end": "2017-10-27"
      },
      "korea": {
        "title": "마음을 잇는 미완성의 노래",
        "start": "2018-02-14",
        "end": "2018-02-20"
      },
      "global": {
        "title": "A Song Unfinished",
        "start": "2018-04-13",
        "end": "2018-04-19"
      },
      "china": {
        "title": "连结思绪的未竟之歌",
        "start": "2019-06-18",
        "end": "2019-06-23"
      }
    }
  },
  {
    "linkId": "Happy_Phantom_Thief_%26_The_Luxury_Cruise",
    "meta": {
      "attribute": "happy"
    },
    "type": "normal",
    "region": {
      "japan": {
        "title": "怪盗ハロハッピーと豪華客船",
        "start": "2017-04-13",
        "end": "2017-04-19"
      },
      "taiwan": {
        "title": "怪盜Hello Happy 與豪華郵輪",
        "start": "2017-10-29",
        "end": "2017-11-06"
      },
      "korea": {
        "title": "괴도 헬로해피와 호화 여객선",
        "start": "2018-02-22",
        "end": "2018-03-02"
      },
      "global": {
        "title": "Happy Phantom Thief & The Luxury Cruise",
        "start": "2018-04-21",
        "end": "2018-04-27"
      },
      "china": {
        "title": "怪盗Hello Happy与豪华客轮",
        "start": "2019-07-02",
        "end": "2019-07-07"
      }
    }
  },
  {
    "linkId": "Rimi%27s_Gift_Of_Song",
    "meta": {
      "attribute": "powerful"
    },
    "type": "normal",
    "region": {
      "japan": {
        "title": "りみのプレゼントソング",
        "start": "2017-04-21",
        "end": "2017-04-28"
      },
      "taiwan": {
        "title": "里美的禮物之歌",
        "start": "2017-12-13",
        "end": "2017-12-20"
      },
      "korea": {
        "title": "리미의 프레젠트 송",
        "start": "2018-03-04",
        "end": "2018-03-11"
      },
      "global": {
        "title": "Rimi's Gift Of Song",
        "start": "2018-04-29",
        "end": "2018-05-05"
      },
      "china": {
        "title": "里美的赠礼之歌",
        "start": "2019-07-09",
        "end": "2019-07-14"
      }
    }
  },
  {
    "linkId": "Searching_For_Stars",
    "meta": {
      "attribute": "pure"
    },
    "type": "normal",
    "region": {
      "japan": {
        "title": "星を探しに",
        "start": "2017-04-30",
        "end": "2017-05-09"
      },
      "taiwan": {
        "title": "一起尋找星星",
        "start": "2017-11-07",
        "end": "2017-11-14"
      },
      "korea": {
        "title": "별을 찾아서",
        "start": "2018-03-13",
        "end": "2018-03-21"
      },
      "global": {
        "title": "Searching For Stars",
        "start": "2018-05-07",
        "end": "2018-05-14"
      },
      "china": {
        "title": "寻觅繁星",
        "start": "2019-07-16",
        "end": "2019-07-21"
      }
    }
  },
  {
    "linkId": "As_Evening_Clears",
    "meta": {
      "attribute": "cool"
    },
    "type": "normal",
    "region": {
      "japan": {
        "title": "夕影、鮮明になって",
        "start": "2017-05-11",
        "end": "2017-05-19"
      },
      "taiwan": {
        "title": "夕陽變得如此鮮明",
        "start": "2017-11-16",
        "end": "2017-11-23"
      },
      "korea": {
        "title": "석양, 선명해지고",
        "start": "2018-03-23",
        "end": "2018-03-31"
      },
      "global": {
        "title": "As Evening Clears",
        "start": "2018-05-16",
        "end": "2018-05-23"
      },
      "china": {
        "title": "日渐鲜明的夕照",
        "start": "2019-07-23",
        "end": "2019-07-28"
      }
    }
  },
  {
    "linkId": "Run_Away_Rabbits!",
    "meta": {
      "attribute": "happy"
    },
    "type": "normal",
    "region": {
      "japan": {
        "title": "うさぎ逃走中",
        "start": "2017-05-23",
        "end": "2017-05-29"
      },
      "taiwan": {
        "title": "小兔子逃走中",
        "start": "2017-11-25",
        "end": "2017-12-02"
      },
      "korea": {
        "title": "토끼는 도망 중!",
        "start": "2018-04-02",
        "end": "2018-04-09"
      },
      "global": {
        "title": "Run Away Rabbits!",
        "start": "2018-05-25",
        "end": "2018-05-31"
      },
      "china": {
        "title": "小兔子脱逃中！",
        "start": "2019-07-30",
        "end": "2019-08-04"
      }
    }
  },
  {
    "linkId": "Past_Aspirations_And_Pastel_Futures",
    "meta": {
      "attribute": "powerful"
    },
    "type": "normal",
    "region": {
      "japan": {
        "title": "あゆみ続けた道、彩られる未来",
        "start": "2017-05-31",
        "end": "2017-06-08"
      },
      "taiwan": {
        "title": "向前邁進的道路，是充滿色彩的未來",
        "start": "2017-12-04",
        "end": "2017-12-11"
      },
      "korea": {
        "title": "계속 걸어온 길, 물들어가는 미래",
        "start": "2018-04-11",
        "end": "2018-04-18"
      },
      "global": {
        "title": "Past Aspirations And Pastel Futures",
        "start": "2018-06-02",
        "end": "2018-06-10"
      },
      "china": {
        "title": "前行之路、映照绚彩未来",
        "start": "2019-08-06",
        "end": "2019-08-11"
      }
    }
  },
  {
    "linkId": "The_Impromptu_Wedding_Dress",
    "meta": {
      "attribute": "pure"
    },
    "type": "normal",
    "region": {
      "japan": {
        "title": "ウェディングドレスは突然に",
        "start": "2017-06-10",
        "end": "2017-06-18"
      },
      "taiwan": {
        "title": "婚紗總是來得如此突然",
        "start": "2018-01-28",
        "end": "2018-02-04"
      },
      "korea": {
        "title": "웨딩드레스는 갑자기",
        "start": "2018-04-20",
        "end": "2018-04-28"
      },
      "global": {
        "title": "The Impromptu Wedding Dress",
        "start": "2018-06-12",
        "end": "2018-06-20"
      },
      "china": {
        "title": "突然而至的婚纱",
        "start": "2019-08-13",
        "end": "2019-08-18"
      }
    }
  },
  {
    "linkId": "Don%27t_leave_me,_Lisa!!!!",
    "meta": {
      "attribute": "cool"
    },
    "type": "normal",
    "region": {
      "japan": {
        "title": "Don't leave me, Lisa!!!!",
        "start": "2017-06-21",
        "end": "2017-06-28"
      },
      "taiwan": {
        "title": "Don't leave me, Lisa!!!!",
        "start": "2017-12-23",
        "end": "2017-12-30"
      },
      "korea": {
        "title": "Don't leave me, Lisa!!!!",
        "start": "2018-04-30",
        "end": "2018-05-07"
      },
      "global": {
        "title": "Don't leave me, Lisa!!!!",
        "start": "2018-06-22",
        "end": "2018-06-30"
      },
      "china": {
        "title": "Don't leave me, Lisa!!!!",
        "start": "2019-06-25",
        "end": "2019-06-30"
      }
    }
  },
  {
    "linkId": "Wish_Upon_a_Tanzaku",
    "meta": {
      "attribute": "happy"
    },
    "type": "normal",
    "region": {
      "japan": {
        "title": "星に願う短冊",
        "start": "2017-06-30",
        "end": "2017-07-09"
      },
      "taiwan": {
        "title": "向星星許願的短籤",
        "start": "2018-01-01",
        "end": "2018-01-08"
      },
      "korea": {
        "title": "별에게 비는 소원",
        "start": "2018-05-09",
        "end": "2018-05-16"
      },
      "global": {
        "title": "Wish Upon a Tanzaku",
        "start": "2018-07-03",
        "end": "2018-07-10"
      },
      "china": {
        "title": "向繁星许愿的诗笺",
        "start": "2019-08-20",
        "end": "2019-08-25"
      }
    }
  },
  {
    "linkId": "Tomoe_SOS!_Ako%27s_Grand_Nursing_Operation",
    "meta": {
      "attribute": "powerful"
    },
    "type": "normal",
    "region": {
      "japan": {
        "title": "巴SOS！あこの看病大作戦",
        "start": "2017-07-11",
        "end": "2017-07-18"
      },
      "taiwan": {
        "title": "巴SOS！亞子的看病大作戦",
        "start": "2018-01-10",
        "end": "2018-01-17"
      },
      "korea": {
        "title": "토모에 SOS! 아코의 간호 대작전",
        "start": "2018-05-18",
        "end": "2018-05-26"
      },
      "global": {
        "title": "Tomoe SOS! Ako's Grand Nursing Operation",
        "start": "2018-07-12",
        "end": "2018-07-20"
      },
      "china": {
        "title": "巴的SOS！亚子的看护大作战",
        "start": "2019-08-27",
        "end": "2019-09-01"
      }
    }
  },
  {
    "linkId": "When_the_Flowers_Bloom",
    "meta": {
      "attribute": "pure"
    },
    "type": "challenge",
    "region": {
      "japan": {
        "title": "つぼみ開く時",
        "start": "2017-07-21",
        "end": "2017-07-29"
      },
      "taiwan": {
        "title": "花苞綻放之時",
        "start": "2018-01-19",
        "end": "2018-01-26"
      },
      "korea": {
        "title": "꽃봉오리가 필 때",
        "start": "2018-05-28",
        "end": "2018-06-05"
      },
      "global": {
        "title": "When the Flowers Bloom",
        "start": "2018-07-22",
        "end": "2018-07-30"
      },
      "china": {
        "title": "花蕾绽放之时",
        "start": "2019-09-03",
        "end": "2019-09-08"
      }
    }
  },
  {
    "linkId": "Happy_Summer_Vacation!",
    "meta": {
      "attribute": "cool"
    },
    "type": "normal",
    "region": {
      "japan": {
        "title": "ハッピーサマーバケーション",
        "start": "2017-07-31",
        "end": "2017-08-08"
      },
      "taiwan": {
